pipeline:
  name: wan2.1-t2v-1.3b
  path: Wan-AI/Wan2.1-T2V-1.3B-Diffusers
  dtype: torch.bfloat16
eval:
  height: 480
  width: 832
  num_steps: 50
  guidance_scale: 6.0
  protocol: fmeuler{num_steps}-g{guidance_scale}
  num_samples: 2
quant:
  calib:
    batch_size: 1
    num_workers: 0
    pin_memory: false
    prefetch_factor: 1
  wgts:
    calib_range:
      element_batch_size: 8
      sample_batch_size: 4
      element_size: 512
      sample_size: -1
    low_rank:
      sample_batch_size: 4
      sample_size: -1
    skips:
    - embed
    - transformer_proj_in
    - transformer_proj_out
    - transformer_norm
    - transformer_add_norm
  ipts:
    calib_range:
      element_batch_size: 8
      sample_batch_size: 4
      element_size: 512
      sample_size: -1
    skips:
    - embed
    - transformer_proj_in
    - transformer_proj_out
    - transformer_norm
    - transformer_add_norm
  smooth:
    proj:
      sample_batch_size: 4
      sample_size: -1

